services:
    panther:
        build:
            # https://symfony.com/doc/current/testing/end_to_end.html#docker-integration
            # Importan: $ must be quoted (as $$) inside dockerfile_inline
            dockerfile_inline: |-
                FROM php:8.5-alpine

                RUN apk add --no-cache php85-pdo_mysql php85-intl icu-dev \
                    && docker-php-ext-install pdo_mysql \
                    && docker-php-ext-configure intl \
                    && docker-php-ext-install intl \
                    && docker-php-ext-enable intl

                # # Xdebug
                # RUN apk add --update --no-cache --virtual .build-deps $$PHPIZE_DEPS linux-headers \
                #    && pecl install xdebug \
                #    && docker-php-ext-enable xdebug \
                #    && apk del -f .build-deps

                # Chromium and ChromeDriver
                ENV PANTHER_NO_SANDBOX 1
                # Not mandatory, but recommended
                ENV PANTHER_CHROME_ARGUMENTS='--disable-dev-shm-usage'
                RUN apk add --no-cache chromium chromium-chromedriver

                # # Firefox and GeckoDriver (optional)
                # ARG GECKODRIVER_VERSION=0.28.0
                # RUN apk add --no-cache firefox libzip-dev; \
                #     docker-php-ext-install zip
                # RUN wget -q https://github.com/mozilla/geckodriver/releases/download/v$$GECKODRIVER_VERSION/geckodriver-v$$GECKODRIVER_VERSION-linux64.tar.gz; \
                #     tar -zxf geckodriver-v$$GECKODRIVER_VERSION-linux64.tar.gz -C /usr/bin; \
                #     rm geckodriver-v$$GECKODRIVER_VERSION-linux64.tar.gz

        volumes:
            - .:/app
        working_dir: /app
        networks:
            - app
            - frontend
        profiles:
            - dev
        environment:
            # https://symfony.com/doc/current/testing/end_to_end.html#configuring-panther-through-environment-variables
            PANTHER_APP_ENV: test
            PANTHER_ERROR_SCREENSHOT_DIR: ./var/error-screenshots
            # https://symfony.com/doc/current/testing/end_to_end.html#changing-the-size-of-the-browser-window
            PANTHER_CHROME_ARGUMENTS: ${PANTHER_CHROME_ARGUMENTS:---disable-dev-shm-usage}
            DEFAULT_LOCALE:

    node:
        image: node:24-alpine
        working_dir: /app
        volumes:
            - ./:/app:delegated
            # - node_modules:/app/node_modules
        profiles:
            - dev
