version: '3'

vars:
  DOCKER_COMPOSE: '{{.TASK_DOCKER_COMPOSE | default "docker compose"}}'

# https://taskfile.dev/usage/#env-files
dotenv: ['.env.local', '.env']

tasks:
  site:install:
    desc: Install site from scratch
    prompt: Really (re)install site?
    cmds:
      - task: compose
        vars:
          TASK_ARGS: down --remove-orphans
      - task: site:update

  site:update:
    desc: Update site
    cmds:
      - task: docker:pull
      - task: compose
        vars:
          TASK_ARGS: up --detach --remove-orphans --wait
      - task: composer
        vars:
          TASK_ARGS: install {{if eq .APP_ENV "prod"}}--no-dev{{end}}
      - task: console
        vars:
          TASK_ARGS: doctrine:migrations:migrate --no-interaction
      - task: site:update:dev
      - task: site:update:prod
      - task: console
        vars:
          TASK_ARGS: cache:clear

  site:update:dev:
    desc: Additional site update commands for "dev"
    if: '[ "$APP_ENV" = "dev" ]'
    cmds:
      - rm -fr var/share/{{.APP_ENV}}
    internal: true

  site:update:prod:
    desc: Additional site update commands for "prod"
    if: '[ "$APP_ENV" = "prod" ]'
    # https://symfony.com/doc/current/frontend/asset_mapper.html#serving-assets-in-dev-vs-prod
    cmds:
      - task: console
        vars:
          TASK_ARGS: asset-map:compile
      - rm -fr var/share/{{.APP_ENV}}
    internal: true

  translations:extract:
    desc: Extract translations
    cmd:
      task: composer
      vars:
        TASK_ARGS: translations-extract

  fixtures:load:
    desc: Load fixtures
    prompt: Really load fixtures?
    cmd:
      task: console
      vars:
        # Don't purge settings
        TASK_ARGS: doctrine:fixtures:load --purge-exclusions=setting --group app --no-interaction

  test:
    desc: Run all tests
    cmds:
      - task: test:integration
      - task: test:application

  test:integration: &test_task
    env:
      APP_ENV: test
    desc: 'Run all {{.TASK | replace "test:" "" }} tests'
    cmd:
      task: compose
      vars:
        TASK_ARGS: exec --env APP_ENV phpfpm php bin/phpunit tests/{{.TASK | replace "test:" "" | title }}

  test:application: *test_task

  test:E2E:
    desc: 'Run all {{.TASK | replace "test:" "" }} tests'
    cmd:
      task: compose
      vars:
        TASK_ARGS: run --build --rm panther bin/phpunit tests/{{.TASK | replace "test:" "" | title }}

  test:playwright:
    env:
      APP_ENV: test
    desc: 'Run all {{.TASK | replace "test:" "" }} tests'
    cmds:
      # - task: site:install
      - task: console
        vars:
          TASK_ARGS: doctrine:fixtures:load --purge-exclusions=setting --group department --no-interaction
      - task: compose
        vars:
          TASK_ARGS: run --env APP_ENV --rm playwright npm install
      - task: compose
        vars:
          TASK_ARGS: run --env APP_ENV --rm playwright npx playwright install
      - task: compose
        vars:
          TASK_ARGS: run --env APP_ENV --rm playwright npx playwright test

  test:playwright:ui:
    env:
      APP_ENV: test
      DISPLAY: ':0'
    desc: 'Run all {{.TASK | replace "test:" "" }} tests'
    cmds:
      - xhost + 127.0.0.1
      - task: compose
        vars:
          TASK_ARGS: run --rm --env APP_ENV --env DISPLAY=host.docker.internal:0 playwright npx playwright test --ui

  compose:
    desc: Run `docker compose` command, e.g. `task {{.TASK}} -- config`
    cmd: '{{.DOCKER_COMPOSE}} {{.TASK_ARGS}} {{.CLI_ARGS}}'

  composer:
    desc: Run `composer` command, e.g. `task {{.TASK}} -- show`
    cmd:
      task: compose
      vars:
        TASK_ARGS: exec --env APP_ENV phpfpm composer {{.TASK_ARGS}}

  php:
    desc: Run PHP, e.g. `task {{.TASK}} -- bin/console`
    cmd:
      task: compose
      vars:
        TASK_ARGS: exec --env APP_ENV phpfpm php {{.TASK_ARGS}}

  console:
    desc: Run Symfony console command, e.g. `task {{.TASK}} -- cache:clear`
    cmd:
      task: php
      vars:
        TASK_ARGS: bin/console {{.TASK_ARGS}}

  coding-standards:apply:
    desc: 'Apply coding standards'
    cmds:
      - task: coding-standards:assets:apply
      - task: coding-standards:composer:apply
      - task: coding-standards:markdown:apply
      - task: coding-standards:php:apply
      - task: coding-standards:twig:apply
      - task: coding-standards:yaml:apply

  coding-standards:check:
    desc: 'Apply coding standards'
    cmds:
      - task: coding-standards:assets:check
      - task: coding-standards:composer:check
      - task: coding-standards:markdown:check
      - task: coding-standards:php:check
      - task: coding-standards:twig:check
      - task: coding-standards:yaml:check

  coding-standards:assets:apply:
    desc: 'Apply coding standards for assets'
    cmd:
      task: compose
      vars:
        TASK_ARGS: run --rm prettier 'assets/' --write

  coding-standards:assets:check:
    desc: 'Apply and check coding standards for assets'
    cmds:
      - task: coding-standards:assets:apply
      - task: compose
        vars:
          TASK_ARGS: run --rm prettier 'assets/' --check

  coding-standards:composer:apply:
    desc: 'Apply coding standards for Composer'
    cmd:
      task: composer
      vars:
        TASK_ARGS: normalize

  coding-standards:composer:check:
    desc: 'Apply and check coding standards for Composer'
    cmds:
      - task: coding-standards:composer:apply
      - task: composer
        vars:
          TASK_ARGS: audit
      - task: composer
        vars:
          TASK_ARGS: normalize --dry-run
      - task: composer
        vars:
          TASK_ARGS: validate --strict

  coding-standards:markdown:apply:
    desc: 'Apply coding standards for Markdown'
    cmds:
      - task: compose
        vars:
          TASK_ARGS: run --rm markdownlint '**/*.md' --fix

  coding-standards:markdown:check:
    desc: 'Apply and check coding standards for Markdown'
    cmds:
      - task: coding-standards:markdown:apply
      - task: compose
        vars:
          TASK_ARGS: run --rm markdownlint '**/*.md'

  coding-standards:php:apply:
    desc: 'Apply coding standards for PHP'
    cmds:
      - task: compose
        vars:
          TASK_ARGS: exec phpfpm vendor/bin/rector
      - task: compose
        vars:
          TASK_ARGS: exec phpfpm vendor/bin/php-cs-fixer fix

  coding-standards:php:check:
    desc: 'Apply and check coding standards for PHP'
    cmds:
      - task: coding-standards:php:apply
      - task: compose
        vars:
          TASK_ARGS: exec phpfpm vendor/bin/rector --dry-run
      - task: compose
        vars:
          TASK_ARGS: exec phpfpm vendor/bin/php-cs-fixer check

  coding-standards:twig:apply:
    desc: 'Apply coding standards for Twig'
    cmds:
      - task: compose
        vars:
          TASK_ARGS: exec phpfpm vendor/bin/twig-cs-fixer fix

  coding-standards:twig:check:
    desc: 'Apply and check coding standards for Twig'
    cmds:
      - task: coding-standards:twig:apply
      - task: compose
        vars:
          TASK_ARGS: exec phpfpm vendor/bin/twig-cs-fixer check

  coding-standards:yaml:apply:
    desc: 'Apply coding standards for YAML'
    cmds:
      - task: compose
        vars:
          TASK_ARGS: run --rm prettier --parser yaml phpstan*.neon '**/*.{yml,yaml}' --write

  coding-standards:yaml:check:
    desc: 'Apply and check coding standards for YAML'
    cmds:
      - task: coding-standards:yaml:apply
      - task: compose
        vars:
          TASK_ARGS: run --rm prettier --parser yaml phpstan*.neon '**/*.{yml,yaml}' --check

  code-analysis:
    desc: 'Run code analysis'
    cmds:
      - task: compose
        vars:
          TASK_ARGS: exec phpfpm vendor/bin/phpstan

  docker:pull:
    desc: 'Pull all development docker images'
    cmds:
      - task: compose
        vars:
          TASK_ARGS: --profile '*' pull

  default:
    cmds:
      - task --list-all
    silent: true

  docs:images:generate:
    desc: 'Generate docs images'
    env:
      PANTHER_CHROME_ARGUMENTS: '--disable-dev-shm-usage --window-size=1024,540'
    cmds:
      - docker compose run --build --env PANTHER_CHROME_ARGUMENTS --rm panther bin/phpunit tests/Docs/GenerateDocsImages.php
      - task docs:images:trim

  docs:images:trim:
    desc: 'Trim docs images'
    # Trim and add top and bottom border
    cmd: docker compose run --rm --entrypoint mogrify imagemagick -background white -trim -gravity north -splice 0x{{.BORDER_WIDTH}}+0+0 -gravity south -splice 0x{{.BORDER_WIDTH}}+0+0 docs/images/*/*.png
    vars:
      BORDER_WIDTH: 16
