name: Code analysis

env:
    COMPOSE_USER: runner

on:
    pull_request:
    push:
        branches:
            - main
            - develop

jobs:
    code-analysis:
        strategy:
            matrix:
                task:
                    - code-analysis:phpstan
                    - code-analysis:mago
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: go-task/setup-task@v2

            - name: Create docker network
              run: |
                  docker network create frontend

            - run: |
                  docker compose run --rm --no-deps phpfpm composer install --no-scripts

            - name: ${{ matrix.task }}
              run: |
                  task ${{ matrix.task }}
